In [14]:
import pandas as pd

#df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
df = pd.DataFrame([[1,10],[2,20]],columns=['A','B'])


df1 = df.apply(lambda x: 1)

print(df)
print(df1)

   A   B
0  1  10
1  2  20
A    1
B    1
dtype: int64

In [18]:
pdf = pd.DataFrame([[1,2],[3,4]])
pdf

   0  1
0  1  2
1  3  4

In [19]:
pdf*pdf

   0   1
0  1   4
1  9  16

In [3]:
(17441/61)/60
import datetime
datetime.datetime.now()

datetime.datetime(2023, 10, 12, 10, 45, 3, 625474)

In [4]:
datetime.datetime.now()

datetime.datetime(2023, 10, 12, 10, 48, 18, 262219)

In [ ]:
datetime.datetime.now()